package co.il.liam.booktobook;

import android.content.Context;
import android.os.AsyncTask;
import android.widget.Toast;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class EmailSender {
    public static void sendEmail(Context context, String to, String subject, String body) {
        new SendEmailTask(context).execute(to, subject, body);
    }

    private static class SendEmailTask extends AsyncTask<String, Void, Boolean> {

        private Context mContext;

        public SendEmailTask(Context context) {
            mContext = context;
        }

        @Override
        protected Boolean doInBackground(String... params) {
            final String username = "BookToBookCS@gmail.com";  // The sender Email
            final String password = "iott wnih yqjk zcyt";  // This password is generated by Google.
            String to = params[0];
            String subject = params[1];
            String body = params[2];

            Properties props = new Properties();
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "465");
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            props.put("mail.smtp.auth", "true");

            Session session = Session.getInstance(props,
                    new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });

            try {
                MimeMessage message = new MimeMessage(session);
                message.setFrom(new InternetAddress(username));
                message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
                message.setSubject(subject);
                message.setText(body);
                Transport.send(message);
                return true; // Email sent successfully
            } catch (MessagingException e) {
                e.printStackTrace();
                return false; // Email sending failed
            }
        }

        @Override
        protected void onPostExecute(Boolean success) {
            if (!success) {
                // Show a toast message indicating fail
                Toast.makeText(mContext, "Failed to send mail", Toast.LENGTH_SHORT).show();
            }
        }
    }
}
